services:
  transaction.db:
    image: postgres
    environment:
      POSTGRES_DB: transaction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/transaction-db:/var/lib/postgresql/data
    
  transaction.api:
    image: transaction.api
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: Transaction.Api/Dockerfile
